version: "3.8"
services:
  api:
    build: .
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
        - ./uploads:/usr/src/app/uploads  # Монтирование папки uploads

  postgres:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/entity

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"



volumes:
  postgres-db: