version: "3.8"
services:
  api:
    build: .
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped

  postgres:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      # ИСПРАВЛЕНО: правильный путь для PostgreSQL данных
      - postgres-db:/var/lib/postgresql/data
      # Дополнительно: backup директория на хосте
      - ./backups:/backups
    restart: unless-stopped
    # Добавляем healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"
    volumes:
      # Сохраняем настройки pgadmin
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres-db:
    driver: local
  pgadmin-data:
    driver: local