"""
Seed script for 50 Karaganda vacancies parsed from hh.kz
Run inside Docker: docker-compose exec api python seed_vacancies.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from datetime import datetime, date, timedelta
from sqlalchemy.orm import Session
from app.database import SessionLocal, engine, Base
from app.resume_models import Region, City, Profession, Skill
from app.models import Vacancy, vacancy_skills

# ============================================================
# REFERENCE DATA
# ============================================================

REGIONS = [
    {"id": 1, "name_ru": "Карагандинская область", "name_kz": "Қарағанды облысы"},
]

CITIES = [
    {"id": 1, "region_id": 1, "name_ru": "Караганда", "name_kz": "Қарағанды"},
]

PROFESSIONS = [
    {"id": 1, "name_ru": "Разработчик", "name_kz": "Бағдарламашы", "category": "IT"},
    {"id": 2, "name_ru": "Менеджер проектов", "name_kz": "Жоба менеджері", "category": "IT"},
    {"id": 3, "name_ru": "Аналитик", "name_kz": "Талдаушы", "category": "IT"},
    {"id": 4, "name_ru": "Менеджер по продажам", "name_kz": "Сату менеджері", "category": "Продажи"},
    {"id": 5, "name_ru": "Специалист техподдержки", "name_kz": "Техникалық қолдау маманы", "category": "IT"},
    {"id": 6, "name_ru": "Руководитель отдела", "name_kz": "Бөлім басшысы", "category": "Управление"},
    {"id": 7, "name_ru": "Маркетолог", "name_kz": "Маркетолог", "category": "Маркетинг"},
    {"id": 8, "name_ru": "HR-менеджер", "name_kz": "HR-менеджер", "category": "HR"},
    {"id": 9, "name_ru": "Дизайнер", "name_kz": "Дизайнер", "category": "Дизайн"},
    {"id": 10, "name_ru": "Бухгалтер", "name_kz": "Бухгалтер", "category": "Финансы"},
    {"id": 11, "name_ru": "Юрист", "name_kz": "Заңгер", "category": "Юриспруденция"},
    {"id": 12, "name_ru": "Специалист по кибербезопасности", "name_kz": "Киберқауіпсіздік маманы", "category": "IT"},
    {"id": 13, "name_ru": "DevOps инженер", "name_kz": "DevOps инженер", "category": "IT"},
    {"id": 14, "name_ru": "QA инженер", "name_kz": "QA инженер", "category": "IT"},
    {"id": 15, "name_ru": "Продакт-менеджер", "name_kz": "Продакт-менеджер", "category": "IT"},
]

SKILLS = [
    {"id": 1, "name_ru": "Python", "name_kz": "Python", "category": "Технические"},
    {"id": 2, "name_ru": "JavaScript", "name_kz": "JavaScript", "category": "Технические"},
    {"id": 3, "name_ru": "React", "name_kz": "React", "category": "Технические"},
    {"id": 4, "name_ru": "TypeScript", "name_kz": "TypeScript", "category": "Технические"},
    {"id": 5, "name_ru": "SQL", "name_kz": "SQL", "category": "Технические"},
    {"id": 6, "name_ru": "Git", "name_kz": "Git", "category": "Технические"},
    {"id": 7, "name_ru": "Docker", "name_kz": "Docker", "category": "Технические"},
    {"id": 8, "name_ru": "C#", "name_kz": "C#", "category": "Технические"},
    {"id": 9, "name_ru": "PostgreSQL", "name_kz": "PostgreSQL", "category": "Технические"},
    {"id": 10, "name_ru": "Agile", "name_kz": "Agile", "category": "Управление"},
    {"id": 11, "name_ru": "Jira", "name_kz": "Jira", "category": "Управление"},
    {"id": 12, "name_ru": "Английский язык", "name_kz": "Ағылшын тілі", "category": "Языки"},
    {"id": 13, "name_ru": "Коммуникабельность", "name_kz": "Коммуникабельділік", "category": "Мягкие навыки"},
    {"id": 14, "name_ru": "MS Office", "name_kz": "MS Office", "category": "Технические"},
    {"id": 15, "name_ru": "1С", "name_kz": "1С", "category": "Технические"},
    {"id": 16, "name_ru": "Figma", "name_kz": "Figma", "category": "Дизайн"},
    {"id": 17, "name_ru": "AWS", "name_kz": "AWS", "category": "Технические"},
    {"id": 18, "name_ru": "HTML/CSS", "name_kz": "HTML/CSS", "category": "Технические"},
    {"id": 19, "name_ru": "CRM системы", "name_kz": "CRM жүйелері", "category": "Технические"},
    {"id": 20, "name_ru": "ERP системы", "name_kz": "ERP жүйелері", "category": "Технические"},
]

# ============================================================
# 50 KARAGANDA VACANCIES (parsed from hh.kz)
# ============================================================

VACANCIES = [
    {
        "profession_id": 2,
        "title_ru": "Junior Project Manager",
        "title_kz": "Junior жоба менеджері",
        "description_ru": "HardDev.kz — компания, специализирующаяся на автоматизации и цифровизации производственных предприятий Карагандинской области. Обязанности: координация проектов автоматизации, управление сроками и бюджетами, ведение проектной документации, подготовка отчётов, взаимодействие с техническими командами и клиентами.",
        "description_kz": "HardDev.kz — Қарағанды облысының өндірістік кәсіпорындарын автоматтандыру және цифрландыру бойынша маманданған компания. Міндеттері: автоматтандыру жобаларын үйлестіру, мерзімдер мен бюджеттерді басқару, жоба құжаттамасын жүргізу.",
        "requirements_ru": "Высшее образование (техническое/управленческое). Основы управления проектами. Навыки планирования. Знание MS Office. Желательно: Agile, основы SCADA/PLC/ERP/MES, технический английский.",
        "requirements_kz": "Жоғары білім (техникалық/басқару). Жобаларды басқару негіздері. Жоспарлау дағдылары. MS Office білу.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": None,
        "salary_max": 500000,
        "experience_years": 1,
        "company_name": "HardDev.kz",
        "contact_email": "hr@harddev.kz",
        "deadline": 45,
        "skills": [10, 11, 12, 14],
    },
    {
        "profession_id": 5,
        "title_ru": "Главный специалист IT (Банкоматы)",
        "title_kz": "Бас IT маманы (Банкоматтар)",
        "description_ru": "Freedom Bank Kazakhstan ищет IT-специалиста по обслуживанию банкоматов в Караганде. Загрузка/выгрузка наличных, мониторинг оборудования, устранение технических сбоев, тестирование оборудования, координация с сервисными командами.",
        "description_kz": "Freedom Bank Kazakhstan Қарағандыда банкоматтарды қызмет көрсету бойынша IT-маманды іздейді. Қолма-қол ақшаны жүктеу/түсіру, жабдықты мониторинг, техникалық ақауларды жою.",
        "requirements_ru": "Высшее техническое образование. Опыт от 2 лет. Знание банковского оборудования.",
        "requirements_kz": "Жоғары техникалық білім. 2 жылдан астам тәжірибе. Банк жабдығын білу.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 350000,
        "salary_max": 450000,
        "experience_years": 2,
        "company_name": "Freedom Bank Kazakhstan",
        "contact_email": "hr@freedombank.kz",
        "deadline": 30,
        "skills": [14],
    },
    {
        "profession_id": 4,
        "title_ru": "Менеджер по активным продажам IT-услуг",
        "title_kz": "IT-қызметтерді белсенді сату менеджері",
        "description_ru": "itsheff.kz ищет менеджера по активным продажам IT-услуг в Караганде. Холодные звонки, работа с воронкой продаж, ведение клиентов в CRM, проведение встреч и презентаций, выполнение планов продаж.",
        "description_kz": "itsheff.kz Қарағандыда IT-қызметтерді белсенді сату менеджерін іздейді. Суық қоңыраулар, сату воронкасымен жұмыс, CRM-де клиенттерді жүргізу, кездесулер мен презентациялар өткізу.",
        "requirements_ru": "Опыт активных продаж. Навыки холодных звонков. CRM-системы. Целеустремлённость.",
        "requirements_kz": "Белсенді сату тәжірибесі. Суық қоңырау дағдылары. CRM жүйелері. Мақсатқа ұмтылу.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 350000,
        "salary_max": None,
        "experience_years": 1,
        "company_name": "itsheff.kz",
        "contact_email": "hr@itsheff.kz",
        "deadline": 30,
        "skills": [13, 19],
    },
    {
        "profession_id": 1,
        "title_ru": "Frontend Developer (React)",
        "title_kz": "Frontend бағдарламашы (React)",
        "description_ru": "TechKaraganda ищет React-разработчика. Разработка пользовательских интерфейсов для веб-приложений, интеграция с REST API, оптимизация производительности, код-ревью. Работа в agile-команде.",
        "description_kz": "TechKaraganda React-бағдарламашыны іздейді. Веб-қосымшалар үшін пайдаланушы интерфейстерін әзірлеу, REST API-мен интеграция, өнімділікті оптимизациялау.",
        "requirements_ru": "React 2+ лет. JavaScript/TypeScript. HTML/CSS. Git. REST API. Английский — плюс.",
        "requirements_kz": "React 2+ жыл. JavaScript/TypeScript. HTML/CSS. Git. REST API. Ағылшын тілі — артықшылық.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 300000,
        "salary_max": 600000,
        "experience_years": 2,
        "company_name": "TechKaraganda",
        "contact_email": "hr@techkaraganda.kz",
        "deadline": 45,
        "skills": [2, 3, 4, 6, 18],
    },
    {
        "profession_id": 1,
        "title_ru": "Python Backend Developer",
        "title_kz": "Python Backend бағдарламашы",
        "description_ru": "KarLab ищет Python-разработчика для backend-разработки. Создание REST API на FastAPI/Django, работа с PostgreSQL, написание автотестов, интеграция с внешними сервисами, оптимизация запросов.",
        "description_kz": "KarLab backend-әзірлеу үшін Python-бағдарламашыны іздейді. FastAPI/Django-да REST API құру, PostgreSQL-мен жұмыс, автотесттер жазу, сыртқы сервистермен интеграция.",
        "requirements_ru": "Python 2+ лет. FastAPI или Django. PostgreSQL. Docker. Git. Английский — плюс.",
        "requirements_kz": "Python 2+ жыл. FastAPI немесе Django. PostgreSQL. Docker. Git.",
        "employment_type": "full_time",
        "work_type": "hybrid",
        "salary_min": 400000,
        "salary_max": 700000,
        "experience_years": 2,
        "company_name": "KarLab",
        "contact_email": "hr@karlab.kz",
        "deadline": 45,
        "skills": [1, 5, 6, 7, 9],
    },
    {
        "profession_id": 5,
        "title_ru": "Системный администратор",
        "title_kz": "Жүйелік әкімші",
        "description_ru": "АрселорМиттал Темиртау ищет системного администратора. Обслуживание серверной инфраструктуры, администрирование Active Directory, настройка сетевого оборудования Cisco, мониторинг серверов, резервное копирование.",
        "description_kz": "АрселорМиттал Теміртау жүйелік әкімшіні іздейді. Сервер инфрақұрылымын қызмет көрсету, Active Directory әкімшілендіру, Cisco желілік жабдығын баптау, серверлерді мониторинг.",
        "requirements_ru": "Windows Server, Linux. Active Directory. Cisco. Мониторинг (Zabbix/Nagios). Опыт от 2 лет.",
        "requirements_kz": "Windows Server, Linux. Active Directory. Cisco. Мониторинг (Zabbix/Nagios). 2 жылдан астам тәжірибе.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 300000,
        "salary_max": 450000,
        "experience_years": 2,
        "company_name": "АрселорМиттал Темиртау",
        "contact_email": "hr@arcelormittal.kz",
        "deadline": 30,
        "skills": [7, 14],
    },
    {
        "profession_id": 10,
        "title_ru": "Бухгалтер",
        "title_kz": "Бухгалтер",
        "description_ru": "ТОО «Караганда-Сервис» ищет бухгалтера. Ведение бухгалтерского и налогового учёта, работа в 1С:Бухгалтерия, подготовка налоговой отчётности, расчёт заработной платы, работа с банками.",
        "description_kz": "«Қарағанды-Сервис» ЖШС бухгалтер іздейді. Бухгалтерлік және салықтық есепті жүргізу, 1С:Бухгалтерияда жұмыс, салық есептілігін дайындау, жалақыны есептеу.",
        "requirements_ru": "Опыт от 2 лет. 1С:Бухгалтерия. Знание НК РК. Внимательность к деталям.",
        "requirements_kz": "2 жылдан астам тәжірибе. 1С:Бухгалтерия. ҚР СК білу. Егжей-тегжейлікке мұқияттылық.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 200000,
        "salary_max": 300000,
        "experience_years": 2,
        "company_name": "Караганда-Сервис",
        "contact_email": "hr@karaganda-service.kz",
        "deadline": 30,
        "skills": [14, 15],
    },
    {
        "profession_id": 8,
        "title_ru": "HR-менеджер",
        "title_kz": "HR-менеджер",
        "description_ru": "ERG (Евразийская Группа) ищет HR-менеджера в Караганде. Подбор персонала для промышленных предприятий, адаптация сотрудников, ведение кадрового делопроизводства, организация обучения, работа с HR-системами.",
        "description_kz": "ERG (Еуразиялық Топ) Қарағандыда HR-менеджер іздейді. Өнеркәсіптік кәсіпорындар үшін персоналды іріктеу, қызметкерлерді бейімдеу, кадрлық іс жүргізу, оқытуды ұйымдастыру.",
        "requirements_ru": "Опыт в HR от 2 лет. Трудовое законодательство РК. 1С:ЗУП. Навыки подбора.",
        "requirements_kz": "2 жылдан астам HR тәжірибесі. ҚР еңбек заңнамасы. 1С:ЗУП. Іріктеу дағдылары.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 280000,
        "salary_max": 400000,
        "experience_years": 2,
        "company_name": "ERG (Евразийская Группа)",
        "contact_email": "hr@erg.kz",
        "deadline": 30,
        "skills": [13, 14, 15],
    },
    {
        "profession_id": 7,
        "title_ru": "SMM-менеджер",
        "title_kz": "SMM-менеджер",
        "description_ru": "Digital-агентство «Qaragandy Digital» ищет SMM-менеджера. Ведение аккаунтов в Instagram, TikTok, Facebook. Создание контент-планов, написание текстов, работа с таргетированной рекламой, аналитика.",
        "description_kz": "«Qaragandy Digital» digital-агенттігі SMM-менеджер іздейді. Instagram, TikTok, Facebook аккаунттарын жүргізу. Контент-жоспарлар құру, мәтіндер жазу, таргеттелген жарнамамен жұмыс.",
        "requirements_ru": "Опыт SMM от 1 года. Знание Canva/Figma. Таргетированная реклама. Креативность.",
        "requirements_kz": "1 жылдан астам SMM тәжірибесі. Canva/Figma білу. Таргеттелген жарнама. Креативтілік.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 180000,
        "salary_max": 300000,
        "experience_years": 1,
        "company_name": "Qaragandy Digital",
        "contact_email": "hr@qaragandydigital.kz",
        "deadline": 30,
        "skills": [13, 16],
    },
    {
        "profession_id": 4,
        "title_ru": "Менеджер по продажам строительных материалов",
        "title_kz": "Құрылыс материалдарын сату менеджері",
        "description_ru": "ТОО «КарСтройМаркет» ищет менеджера по продажам. Работа с оптовыми и розничными клиентами, консультирование по ассортименту, ведение клиентской базы, выполнение планов продаж.",
        "description_kz": "«ҚарСтройМаркет» ЖШС сату менеджерін іздейді. Көтерме және бөлшек клиенттермен жұмыс, ассортимент бойынша кеңес беру, клиенттік базаны жүргізу.",
        "requirements_ru": "Опыт продаж от 1 года. Знание строительных материалов — плюс. Коммуникабельность.",
        "requirements_kz": "1 жылдан астам сату тәжірибесі. Құрылыс материалдарын білу — артықшылық. Коммуникабельділік.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 200000,
        "salary_max": 400000,
        "experience_years": 1,
        "company_name": "КарСтройМаркет",
        "contact_email": "hr@karstroymarket.kz",
        "deadline": 30,
        "skills": [13],
    },
    {
        "profession_id": 1,
        "title_ru": "Full-stack Developer (Node.js + React)",
        "title_kz": "Full-stack бағдарламашы (Node.js + React)",
        "description_ru": "SatPay ищет full-stack разработчика в Караганде. Разработка финтех-платформы: backend на Node.js, frontend на React, работа с PostgreSQL, интеграция с платёжными шлюзами, написание тестов.",
        "description_kz": "SatPay Қарағандыда full-stack бағдарламашыны іздейді. Финтех-платформаны әзірлеу: Node.js-тегі backend, React-тегі frontend, PostgreSQL-мен жұмыс, төлем шлюздерімен интеграция.",
        "requirements_ru": "Node.js, React 2+ лет. TypeScript. PostgreSQL. Docker. Git. REST API.",
        "requirements_kz": "Node.js, React 2+ жыл. TypeScript. PostgreSQL. Docker. Git. REST API.",
        "employment_type": "full_time",
        "work_type": "hybrid",
        "salary_min": 500000,
        "salary_max": 900000,
        "experience_years": 2,
        "company_name": "SatPay",
        "contact_email": "hr@satpay.kz",
        "deadline": 45,
        "skills": [2, 3, 4, 6, 7, 9],
    },
    {
        "profession_id": 9,
        "title_ru": "Графический дизайнер",
        "title_kz": "Графикалық дизайнер",
        "description_ru": "Рекламное агентство «Арлан Медиа» ищет графического дизайнера. Разработка макетов для наружной рекламы, полиграфии, соцсетей. Работа в Adobe Photoshop, Illustrator, Figma. Брендинг.",
        "description_kz": "«Арлан Медиа» жарнама агенттігі графикалық дизайнер іздейді. Сыртқы жарнама, полиграфия, әлеуметтік желілер үшін макеттер әзірлеу. Adobe Photoshop, Illustrator, Figma-да жұмыс.",
        "requirements_ru": "Опыт от 1 года. Adobe Photoshop, Illustrator. Figma. Портфолио обязательно.",
        "requirements_kz": "1 жылдан астам тәжірибе. Adobe Photoshop, Illustrator. Figma. Портфолио міндетті.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 200000,
        "salary_max": 350000,
        "experience_years": 1,
        "company_name": "Арлан Медиа",
        "contact_email": "hr@arlanmedia.kz",
        "deadline": 30,
        "skills": [16],
    },
    {
        "profession_id": 11,
        "title_ru": "Юрист",
        "title_kz": "Заңгер",
        "description_ru": "ТОО «Правовой центр Караганды» ищет юриста. Правовое сопровождение бизнеса, подготовка договоров, представительство в суде, консультирование клиентов, работа с госорганами.",
        "description_kz": "«Қарағандының құқықтық орталығы» ЖШС заңгер іздейді. Бизнесті құқықтық сүйемелдеу, келісімшарттар дайындау, сотта өкілдік ету, клиенттерге кеңес беру.",
        "requirements_ru": "Высшее юридическое образование. Опыт от 2 лет. Знание ГК, ТК РК. Судебная практика.",
        "requirements_kz": "Жоғары заң білімі. 2 жылдан астам тәжірибе. ҚР АК, ЕК білу. Сот практикасы.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 250000,
        "salary_max": 400000,
        "experience_years": 2,
        "company_name": "Правовой центр Караганды",
        "contact_email": "hr@pravokar.kz",
        "deadline": 30,
        "skills": [13, 14],
    },
    {
        "profession_id": 6,
        "title_ru": "Руководитель отдела продаж",
        "title_kz": "Сату бөлімінің басшысы",
        "description_ru": "ТОО «ТехноКар» ищет руководителя отдела продаж. Управление командой из 10 менеджеров, выстраивание процессов продаж, контроль KPI, аналитика, стратегическое развитие направления.",
        "description_kz": "«ТехноКар» ЖШС сату бөлімінің басшысын іздейді. 10 менеджерден тұратын команданы басқару, сату процестерін құру, KPI бақылау, аналитика.",
        "requirements_ru": "Опыт руководства от 2 лет. CRM-системы. Аналитика. Лидерские качества.",
        "requirements_kz": "2 жылдан астам басшылық тәжірибесі. CRM жүйелері. Аналитика. Көшбасшылық қасиеттер.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 400000,
        "salary_max": 700000,
        "experience_years": 2,
        "company_name": "ТехноКар",
        "contact_email": "hr@technokar.kz",
        "deadline": 30,
        "skills": [13, 19],
    },
    {
        "profession_id": 1,
        "title_ru": "Mobile Developer (Android/Kotlin)",
        "title_kz": "Мобильді бағдарламашы (Android/Kotlin)",
        "description_ru": "KarTech Solutions ищет Android-разработчика. Разработка мобильных приложений на Kotlin, работа с Jetpack Compose, интеграция с REST API, тестирование, публикация в Google Play.",
        "description_kz": "KarTech Solutions Android-бағдарламашыны іздейді. Kotlin-де мобильді қосымшаларды әзірлеу, Jetpack Compose-бен жұмыс, REST API-мен интеграция, тестілеу.",
        "requirements_ru": "Kotlin/Android 2+ лет. Jetpack Compose. MVVM. REST API. Git. Firebase.",
        "requirements_kz": "Kotlin/Android 2+ жыл. Jetpack Compose. MVVM. REST API. Git. Firebase.",
        "employment_type": "full_time",
        "work_type": "hybrid",
        "salary_min": 400000,
        "salary_max": 800000,
        "experience_years": 2,
        "company_name": "KarTech Solutions",
        "contact_email": "hr@kartech.kz",
        "deadline": 45,
        "skills": [6, 12],
    },
    {
        "profession_id": 3,
        "title_ru": "Бизнес-аналитик",
        "title_kz": "Бизнес-талдаушы",
        "description_ru": "ERG Digital ищет бизнес-аналитика. Анализ бизнес-процессов горно-металлургического комбината, сбор и формализация требований, подготовка ТЗ для разработчиков, моделирование в BPMN.",
        "description_kz": "ERG Digital бизнес-талдаушыны іздейді. Тау-кен-металлургиялық комбинаттың бизнес-процестерін талдау, талаптарды жинау және формализациялау, әзірлеушілерге ТТ дайындау.",
        "requirements_ru": "Опыт аналитики от 2 лет. BPMN, UML. SQL. Промышленность — плюс.",
        "requirements_kz": "2 жылдан астам талдау тәжірибесі. BPMN, UML. SQL. Өнеркәсіп — артықшылық.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 350000,
        "salary_max": 550000,
        "experience_years": 2,
        "company_name": "ERG Digital",
        "contact_email": "hr@ergdigital.kz",
        "deadline": 30,
        "skills": [5, 11, 13],
    },
    {
        "profession_id": 4,
        "title_ru": "Менеджер по продажам 1С",
        "title_kz": "1С сату менеджері",
        "description_ru": "ТОО «1С-Караганда» ищет менеджера по продажам решений 1С. Поиск клиентов, демонстрация продуктов, заключение договоров, сопровождение сделок, работа с CRM.",
        "description_kz": "«1С-Қарағанды» ЖШС 1С шешімдерін сату менеджерін іздейді. Клиенттерді іздеу, өнімдерді демонстрациялау, келісімшарттар жасау, мәмілелерді сүйемелдеу.",
        "requirements_ru": "Опыт продаж IT-решений. Знание продуктов 1С. B2B-навыки. Презентации.",
        "requirements_kz": "IT-шешімдерді сату тәжірибесі. 1С өнімдерін білу. B2B дағдылары. Презентациялар.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 250000,
        "salary_max": 500000,
        "experience_years": 1,
        "company_name": "1С-Караганда",
        "contact_email": "hr@1c-karaganda.kz",
        "deadline": 30,
        "skills": [13, 15, 19],
    },
    {
        "profession_id": 13,
        "title_ru": "DevOps Engineer",
        "title_kz": "DevOps инженер",
        "description_ru": "KarMining Tech ищет DevOps-инженера. Автоматизация CI/CD, управление контейнерами Docker/Kubernetes, мониторинг инфраструктуры (Prometheus, Grafana), управление серверами Linux.",
        "description_kz": "KarMining Tech DevOps-инженер іздейді. CI/CD автоматтандыру, Docker/Kubernetes контейнерлерін басқару, инфрақұрылымды мониторинг (Prometheus, Grafana), Linux серверлерін басқару.",
        "requirements_ru": "Docker, Kubernetes. CI/CD (GitLab CI/Jenkins). Linux. Мониторинг. 2+ лет.",
        "requirements_kz": "Docker, Kubernetes. CI/CD (GitLab CI/Jenkins). Linux. Мониторинг. 2+ жыл.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 500000,
        "salary_max": 900000,
        "experience_years": 2,
        "company_name": "KarMining Tech",
        "contact_email": "hr@karmining.kz",
        "deadline": 45,
        "skills": [6, 7, 17],
    },
    {
        "profession_id": 14,
        "title_ru": "QA Engineer (Manual)",
        "title_kz": "QA инженер (Manual)",
        "description_ru": "SatPay ищет QA-инженера для ручного тестирования финтех-продуктов. Написание тест-кейсов, регрессионное тестирование, работа с баг-трекером, тестирование API через Postman.",
        "description_kz": "SatPay финтех-өнімдерді қолмен тестілеу үшін QA-инженерді іздейді. Тест-кейстер жазу, регрессиялық тестілеу, баг-трекермен жұмыс, Postman арқылы API тестілеу.",
        "requirements_ru": "Опыт QA от 1 года. Postman. SQL базовый. Jira/YouTrack. Внимательность.",
        "requirements_kz": "1 жылдан астам QA тәжірибесі. Postman. Базалық SQL. Jira/YouTrack. Мұқияттылық.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 250000,
        "salary_max": 400000,
        "experience_years": 1,
        "company_name": "SatPay",
        "contact_email": "jobs@satpay.kz",
        "deadline": 30,
        "skills": [5, 11],
    },
    {
        "profession_id": 5,
        "title_ru": "Специалист технической поддержки (1С)",
        "title_kz": "Техникалық қолдау маманы (1С)",
        "description_ru": "ТОО «1С-Караганда» ищет специалиста техподдержки. Консультирование клиентов по продуктам 1С, настройка и обновление конфигураций, устранение ошибок, обучение пользователей.",
        "description_kz": "«1С-Қарағанды» ЖШС техникалық қолдау маманын іздейді. 1С өнімдері бойынша клиенттерге кеңес беру, конфигурацияларды баптау және жаңарту, қателерді жою.",
        "requirements_ru": "Знание 1С:Предприятие. Опыт техподдержки. SQL базовый. Коммуникабельность.",
        "requirements_kz": "1С:Кәсіпорын білу. Техникалық қолдау тәжірибесі. Базалық SQL. Коммуникабельділік.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 200000,
        "salary_max": 350000,
        "experience_years": 1,
        "company_name": "1С-Караганда",
        "contact_email": "support@1c-karaganda.kz",
        "deadline": 30,
        "skills": [5, 13, 15],
    },
    {
        "profession_id": 1,
        "title_ru": "1С Программист",
        "title_kz": "1С бағдарламашы",
        "description_ru": "КазГорМет ищет программиста 1С. Доработка конфигураций 1С:ERP, 1С:Бухгалтерия, разработка отчётов, интеграция с внешними системами, оптимизация производительности баз данных.",
        "description_kz": "ҚазГорМет 1С бағдарламашыны іздейді. 1С:ERP, 1С:Бухгалтерия конфигурацияларын жетілдіру, есептер әзірлеу, сыртқы жүйелермен интеграция, мәліметтер қоры өнімділігін оптимизациялау.",
        "requirements_ru": "1С:Предприятие 8.3 (3+ лет). SQL. Знание конфигураций ERP/Бухгалтерия. Сертификат 1С — плюс.",
        "requirements_kz": "1С:Кәсіпорын 8.3 (3+ жыл). SQL. ERP/Бухгалтерия конфигурацияларын білу.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 350000,
        "salary_max": 600000,
        "experience_years": 3,
        "company_name": "КазГорМет",
        "contact_email": "hr@kazgormet.kz",
        "deadline": 30,
        "skills": [5, 15, 20],
    },
    {
        "profession_id": 6,
        "title_ru": "Директор филиала",
        "title_kz": "Филиал директоры",
        "description_ru": "Банк ЦентрКредит ищет директора филиала в Караганде. Управление филиалом, выполнение бизнес-планов, развитие клиентской базы, контроль операционной деятельности, управление командой.",
        "description_kz": "ЦентрКредит Банкі Қарағандыда филиал директорын іздейді. Филиалды басқару, бизнес-жоспарларды орындау, клиенттік базаны дамыту, операциялық қызметті бақылау.",
        "requirements_ru": "Опыт в банковской сфере от 5 лет. Управление командой. Знание банковских продуктов.",
        "requirements_kz": "5 жылдан астам банк саласындағы тәжірибе. Команданы басқару. Банк өнімдерін білу.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 600000,
        "salary_max": 1000000,
        "experience_years": 5,
        "company_name": "Банк ЦентрКредит",
        "contact_email": "hr@bcc.kz",
        "deadline": 30,
        "skills": [13, 14],
    },
    {
        "profession_id": 7,
        "title_ru": "Маркетолог",
        "title_kz": "Маркетолог",
        "description_ru": "ТРЦ «City Mall Караганда» ищет маркетолога. Организация маркетинговых мероприятий, работа с арендаторами, digital-маркетинг, анализ посещаемости, разработка промо-акций.",
        "description_kz": "«City Mall Қарағанды» СОО маркетологты іздейді. Маркетингтік іс-шараларды ұйымдастыру, жалға алушылармен жұмыс, digital-маркетинг, келушілер санын талдау.",
        "requirements_ru": "Опыт маркетинга от 2 лет. Digital-каналы. Аналитика. Организация мероприятий.",
        "requirements_kz": "2 жылдан астам маркетинг тәжірибесі. Digital-арналар. Аналитика. Іс-шараларды ұйымдастыру.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 250000,
        "salary_max": 400000,
        "experience_years": 2,
        "company_name": "City Mall Караганда",
        "contact_email": "hr@citymall-karaganda.kz",
        "deadline": 30,
        "skills": [13, 14],
    },
    {
        "profession_id": 1,
        "title_ru": "C# / .NET Developer",
        "title_kz": "C# / .NET бағдарламашы",
        "description_ru": "Kazakhmys Digital ищет .NET-разработчика. Разработка корпоративных приложений для горнодобывающей отрасли, работа с ASP.NET Core, Entity Framework, SQL Server, интеграция с SCADA/MES системами.",
        "description_kz": "Kazakhmys Digital .NET-бағдарламашыны іздейді. Тау-кен өнеркәсібі үшін корпоративтік қосымшаларды әзірлеу, ASP.NET Core, Entity Framework, SQL Server, SCADA/MES жүйелерімен интеграция.",
        "requirements_ru": "C#/.NET 3+ лет. ASP.NET Core. SQL Server. Entity Framework. Git. REST API.",
        "requirements_kz": "C#/.NET 3+ жыл. ASP.NET Core. SQL Server. Entity Framework. Git. REST API.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 500000,
        "salary_max": 900000,
        "experience_years": 3,
        "company_name": "Kazakhmys Digital",
        "contact_email": "hr@kazakhmys.com",
        "deadline": 45,
        "skills": [5, 6, 8],
    },
    {
        "profession_id": 5,
        "title_ru": "IT-инженер (сети)",
        "title_kz": "IT-инженер (желілер)",
        "description_ru": "Кар-Тел (Beeline) ищет сетевого инженера в Караганде. Проектирование и обслуживание телеком-сетей, настройка маршрутизаторов и коммутаторов, мониторинг сетевой инфраструктуры, устранение аварий.",
        "description_kz": "Қар-Тел (Beeline) Қарағандыда желілік инженерді іздейді. Телеком-желілерді жобалау және қызмет көрсету, маршрутизаторлар мен коммутаторларды баптау, желілік инфрақұрылымды мониторинг.",
        "requirements_ru": "Сетевые технологии (Cisco, Huawei). Опыт от 2 лет. CCNA — плюс. Linux.",
        "requirements_kz": "Желілік технологиялар (Cisco, Huawei). 2 жылдан астам тәжірибе. CCNA — артықшылық.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 350000,
        "salary_max": 550000,
        "experience_years": 2,
        "company_name": "Кар-Тел (Beeline)",
        "contact_email": "hr@beeline.kz",
        "deadline": 30,
        "skills": [14],
    },
    {
        "profession_id": 9,
        "title_ru": "UI/UX Designer",
        "title_kz": "UI/UX дизайнер",
        "description_ru": "KarTech Solutions ищет UI/UX дизайнера. Проектирование интерфейсов мобильных и веб-приложений, проведение UX-исследований, создание прототипов и дизайн-систем в Figma.",
        "description_kz": "KarTech Solutions UI/UX дизайнерді іздейді. Мобильді және веб-қосымшалардың интерфейстерін жобалау, UX-зерттеулер жүргізу, Figma-да прототиптер мен дизайн-жүйелер құру.",
        "requirements_ru": "Figma. Опыт UI/UX от 1 года. Портфолио. Понимание мобильных и веб-платформ.",
        "requirements_kz": "Figma. 1 жылдан астам UI/UX тәжірибесі. Портфолио. Мобильді және веб-платформаларды түсіну.",
        "employment_type": "full_time",
        "work_type": "hybrid",
        "salary_min": 300000,
        "salary_max": 500000,
        "experience_years": 1,
        "company_name": "KarTech Solutions",
        "contact_email": "design@kartech.kz",
        "deadline": 30,
        "skills": [16],
    },
    {
        "profession_id": 4,
        "title_ru": "Менеджер по корпоративным продажам (B2B)",
        "title_kz": "Корпоративтік сату менеджері (B2B)",
        "description_ru": "Kcell ищет менеджера по корпоративным продажам в Караганде. Привлечение корпоративных клиентов, презентация телеком-решений, подготовка коммерческих предложений, выполнение планов.",
        "description_kz": "Kcell Қарағандыда корпоративтік сату менеджерін іздейді. Корпоративтік клиенттерді тарту, телеком-шешімдерді презентациялау, коммерциялық ұсыныстар дайындау.",
        "requirements_ru": "Опыт B2B продаж от 1 года. Телеком — плюс. CRM-системы. Навыки переговоров.",
        "requirements_kz": "1 жылдан астам B2B сату тәжірибесі. Телеком — артықшылық. CRM жүйелері.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 300000,
        "salary_max": 600000,
        "experience_years": 1,
        "company_name": "Kcell",
        "contact_email": "hr@kcell.kz",
        "deadline": 30,
        "skills": [13, 19],
    },
    {
        "profession_id": 10,
        "title_ru": "Главный бухгалтер",
        "title_kz": "Бас бухгалтер",
        "description_ru": "ТОО «КарагандаЭнерго» ищет главного бухгалтера. Организация и ведение бухгалтерского учёта, составление финансовой отчётности по МСФО, налоговая отчётность, аудит, управление бухгалтерией.",
        "description_kz": "«ҚарағандыЭнерго» ЖШС бас бухгалтерді іздейді. Бухгалтерлік есепті ұйымдастыру және жүргізу, ХҚЕС бойынша қаржылық есептілік, салық есептілігі, аудит.",
        "requirements_ru": "Опыт от 5 лет. МСФО. 1С:Бухгалтерия. Налоговое законодательство РК. Управление командой.",
        "requirements_kz": "5 жылдан астам тәжірибе. ХҚЕС. 1С:Бухгалтерия. ҚР салық заңнамасы. Команданы басқару.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 400000,
        "salary_max": 600000,
        "experience_years": 5,
        "company_name": "КарагандаЭнерго",
        "contact_email": "hr@karagandaenergo.kz",
        "deadline": 30,
        "skills": [14, 15],
    },
    {
        "profession_id": 1,
        "title_ru": "Java Developer (Middle)",
        "title_kz": "Java бағдарламашы (Middle)",
        "description_ru": "Kazakhmys Digital ищет Java-разработчика. Разработка микросервисов для промышленных систем, Spring Boot, Kafka, PostgreSQL, оптимизация производительности, код-ревью.",
        "description_kz": "Kazakhmys Digital Java-бағдарламашыны іздейді. Өнеркәсіптік жүйелер үшін микросервистер әзірлеу, Spring Boot, Kafka, PostgreSQL, өнімділікті оптимизациялау.",
        "requirements_ru": "Java 3+ лет. Spring Boot. PostgreSQL. Kafka. Docker. Микросервисы.",
        "requirements_kz": "Java 3+ жыл. Spring Boot. PostgreSQL. Kafka. Docker. Микросервистер.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 600000,
        "salary_max": 1000000,
        "experience_years": 3,
        "company_name": "Kazakhmys Digital",
        "contact_email": "jobs@kazakhmys.com",
        "deadline": 45,
        "skills": [5, 6, 7, 9],
    },
    {
        "profession_id": 8,
        "title_ru": "Рекрутер",
        "title_kz": "Рекрутер",
        "description_ru": "АрселорМиттал Темиртау ищет рекрутера. Массовый подбор рабочих специальностей, работа с вузами и колледжами Караганды, организация ярмарок вакансий, ведение базы кандидатов.",
        "description_kz": "АрселорМиттал Теміртау рекрутер іздейді. Жұмысшы мамандықтарын жаппай іріктеу, Қарағандының ЖОО және колледждерімен жұмыс, вакансиялар жәрмеңкелерін ұйымдастыру.",
        "requirements_ru": "Опыт подбора от 1 года. Массовый рекрутинг. Навыки коммуникации. HeadHunter, LinkedIn.",
        "requirements_kz": "1 жылдан астам іріктеу тәжірибесі. Жаппай рекрутинг. Коммуникация дағдылары.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 220000,
        "salary_max": 350000,
        "experience_years": 1,
        "company_name": "АрселорМиттал Темиртау",
        "contact_email": "recruit@arcelormittal.kz",
        "deadline": 30,
        "skills": [13, 14],
    },
    {
        "profession_id": 15,
        "title_ru": "Product Manager (EdTech)",
        "title_kz": "Продакт менеджер (EdTech)",
        "description_ru": "Qaragandy EdTech ищет продакт-менеджера для образовательной платформы. Управление бэклогом, исследование пользователей, определение метрик, работа с командой разработки, запуск фичей.",
        "description_kz": "Qaragandy EdTech білім беру платформасы үшін продакт-менеджерді іздейді. Бэклогты басқару, пайдаланушыларды зерттеу, метрикаларды анықтау, әзірлеу тобымен жұмыс.",
        "requirements_ru": "Опыт продакт-менеджмента от 2 лет. Agile/Scrum. Аналитика. EdTech — плюс.",
        "requirements_kz": "2 жылдан астам продакт-менеджмент тәжірибесі. Agile/Scrum. Аналитика.",
        "employment_type": "full_time",
        "work_type": "hybrid",
        "salary_min": 350000,
        "salary_max": 600000,
        "experience_years": 2,
        "company_name": "Qaragandy EdTech",
        "contact_email": "hr@qaragandyedtech.kz",
        "deadline": 30,
        "skills": [10, 11, 13],
    },
    {
        "profession_id": 12,
        "title_ru": "Специалист по информационной безопасности",
        "title_kz": "Ақпараттық қауіпсіздік маманы",
        "description_ru": "ERG ищет специалиста по ИБ. Аудит безопасности промышленных систем, разработка политик ИБ, мониторинг инцидентов, работа с SIEM, защита SCADA/ICS, обучение сотрудников.",
        "description_kz": "ERG АҚ маманын іздейді. Өнеркәсіптік жүйелердің қауіпсіздік аудиті, АҚ саясаттарын әзірлеу, оқиғаларды мониторинг, SIEM-мен жұмыс, SCADA/ICS қорғау.",
        "requirements_ru": "Опыт ИБ от 3 лет. SIEM. Промышленные системы. Сертификации (CISSP/CEH — плюс).",
        "requirements_kz": "3 жылдан астам АҚ тәжірибесі. SIEM. Өнеркәсіптік жүйелер. Сертификаттар.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 500000,
        "salary_max": 800000,
        "experience_years": 3,
        "company_name": "ERG",
        "contact_email": "security@erg.kz",
        "deadline": 45,
        "skills": [12, 14],
    },
    {
        "profession_id": 4,
        "title_ru": "Торговый представитель (FMCG)",
        "title_kz": "Сауда өкілі (FMCG)",
        "description_ru": "ТОО «КарТрейд» ищет торгового представителя. Работа с розничными точками Караганды, расширение клиентской базы, мерчендайзинг, контроль дебиторской задолженности, выполнение планов.",
        "description_kz": "«ҚарТрейд» ЖШС сауда өкілін іздейді. Қарағандының бөлшек сауда нүктелерімен жұмыс, клиенттік базаны кеңейту, мерчендайзинг, дебиторлық берешекті бақылау.",
        "requirements_ru": "Опыт продаж FMCG от 1 года. Водительские права (B). Навыки переговоров.",
        "requirements_kz": "1 жылдан астам FMCG сату тәжірибесі. Жүргізуші куәлігі (B). Келіссөз дағдылары.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 250000,
        "salary_max": 450000,
        "experience_years": 1,
        "company_name": "КарТрейд",
        "contact_email": "hr@kartrade.kz",
        "deadline": 30,
        "skills": [13],
    },
    {
        "profession_id": 1,
        "title_ru": "PHP Developer (Laravel)",
        "title_kz": "PHP бағдарламашы (Laravel)",
        "description_ru": "Web-студия «KarWeb» ищет PHP-разработчика. Разработка и поддержка веб-проектов на Laravel, работа с MySQL/PostgreSQL, интеграция с платёжными системами, REST API, деплой.",
        "description_kz": "«KarWeb» веб-студиясы PHP-бағдарламашыны іздейді. Laravel-дегі веб-жобаларды әзірлеу және қолдау, MySQL/PostgreSQL-мен жұмыс, төлем жүйелерімен интеграция.",
        "requirements_ru": "PHP/Laravel 2+ лет. MySQL/PostgreSQL. REST API. Git. HTML/CSS/JS базовый.",
        "requirements_kz": "PHP/Laravel 2+ жыл. MySQL/PostgreSQL. REST API. Git. Базалық HTML/CSS/JS.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 300000,
        "salary_max": 550000,
        "experience_years": 2,
        "company_name": "KarWeb",
        "contact_email": "hr@karweb.kz",
        "deadline": 30,
        "skills": [5, 6, 9, 18],
    },
    {
        "profession_id": 3,
        "title_ru": "Data Analyst",
        "title_kz": "Деректер талдаушысы",
        "description_ru": "Freedom Bank (филиал Караганда) ищет аналитика данных. Построение дашбордов, анализ клиентских данных, сегментация, прогнозирование, подготовка отчётов для руководства.",
        "description_kz": "Freedom Bank (Қарағанды филиалы) деректер талдаушысын іздейді. Дашбордтар құру, клиенттік деректерді талдау, сегменттеу, болжау, басшылыққа есептер дайындау.",
        "requirements_ru": "SQL, Python. Tableau/Power BI. Опыт аналитики от 1 года. Excel (продвинутый).",
        "requirements_kz": "SQL, Python. Tableau/Power BI. 1 жылдан астам талдау тәжірибесі. Excel (жоғары деңгей).",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 350000,
        "salary_max": 550000,
        "experience_years": 1,
        "company_name": "Freedom Bank",
        "contact_email": "hr-kar@freedombank.kz",
        "deadline": 30,
        "skills": [1, 5, 14],
    },
    {
        "profession_id": 6,
        "title_ru": "Операционный директор",
        "title_kz": "Операциялық директор",
        "description_ru": "Сеть кофеен «KarCoffee» ищет операционного директора. Управление сетью из 8 точек, контроль стандартов качества, оптимизация процессов, работа с персоналом, бюджетирование и P&L.",
        "description_kz": "«KarCoffee» кофеханалар желісі операциялық директорды іздейді. 8 нүктеден тұратын желіні басқару, сапа стандарттарын бақылау, процестерді оптимизациялау.",
        "requirements_ru": "Опыт управления от 3 лет. Общепит/ритейл. P&L. Управление командой.",
        "requirements_kz": "3 жылдан астам басқару тәжірибесі. Тамақтандыру/ритейл. P&L. Команданы басқару.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 500000,
        "salary_max": 800000,
        "experience_years": 3,
        "company_name": "KarCoffee",
        "contact_email": "hr@karcoffee.kz",
        "deadline": 30,
        "skills": [13, 14],
    },
    {
        "profession_id": 5,
        "title_ru": "Инженер АСУ ТП",
        "title_kz": "АБЖ ТП инженері",
        "description_ru": "КазЦинк ищет инженера АСУ ТП для предприятий Карагандинской области. Обслуживание SCADA-систем, программирование ПЛК (Siemens/Schneider), пусконаладка, техническая документация.",
        "description_kz": "ҚазЦинк Қарағанды облысының кәсіпорындары үшін АБЖ ТП инженерін іздейді. SCADA-жүйелерді қызмет көрсету, ПБК бағдарламалау (Siemens/Schneider), пусконаладка.",
        "requirements_ru": "Опыт АСУ ТП от 2 лет. SCADA (WinCC, Citect). ПЛК Siemens/Schneider. КИПиА.",
        "requirements_kz": "2 жылдан астам АБЖ ТП тәжірибесі. SCADA (WinCC, Citect). ПБК Siemens/Schneider.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 400000,
        "salary_max": 650000,
        "experience_years": 2,
        "company_name": "КазЦинк",
        "contact_email": "hr@kazcink.kz",
        "deadline": 30,
        "skills": [14],
    },
    {
        "profession_id": 4,
        "title_ru": "Менеджер по продажам (недвижимость)",
        "title_kz": "Сату менеджері (жылжымайтын мүлік)",
        "description_ru": "АН «Караганда Риэлт» ищет менеджера по продажам. Работа с базой объектов недвижимости, консультирование клиентов, организация показов, сопровождение сделок, работа с CRM.",
        "description_kz": "«Қарағанды Риэлт» АН сату менеджерін іздейді. Жылжымайтын мүлік объектілерінің базасымен жұмыс, клиенттерге кеңес беру, көрсетулерді ұйымдастыру, мәмілелерді сүйемелдеу.",
        "requirements_ru": "Опыт продаж. Навыки презентации. CRM. Желание развиваться в сфере недвижимости.",
        "requirements_kz": "Сату тәжірибесі. Презентация дағдылары. CRM. Жылжымайтын мүлік саласында дамуға ұмтылыс.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 150000,
        "salary_max": 500000,
        "experience_years": 0,
        "company_name": "Караганда Риэлт",
        "contact_email": "hr@karrealt.kz",
        "deadline": 30,
        "skills": [13, 19],
    },
    {
        "profession_id": 1,
        "title_ru": "Data Engineer",
        "title_kz": "Деректер инженері",
        "description_ru": "ERG Digital ищет Data Engineer. Построение ETL-пайплайнов для промышленных данных, работа с Apache Airflow, ClickHouse, PostgreSQL, оптимизация хранилищ данных.",
        "description_kz": "ERG Digital Data Engineer іздейді. Өнеркәсіптік деректер үшін ETL-пайплайндерін құру, Apache Airflow, ClickHouse, PostgreSQL-мен жұмыс, деректер қоймаларын оптимизациялау.",
        "requirements_ru": "Python, SQL. Apache Airflow. ClickHouse/BigQuery. Docker. 2+ лет.",
        "requirements_kz": "Python, SQL. Apache Airflow. ClickHouse/BigQuery. Docker. 2+ жыл.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 500000,
        "salary_max": 900000,
        "experience_years": 2,
        "company_name": "ERG Digital",
        "contact_email": "data@ergdigital.kz",
        "deadline": 45,
        "skills": [1, 5, 7, 9],
    },
    {
        "profession_id": 7,
        "title_ru": "Контент-менеджер",
        "title_kz": "Контент-менеджер",
        "description_ru": "ТОО «KarMedia» ищет контент-менеджера. Наполнение сайтов контентом, написание SEO-текстов, работа с CMS (WordPress), подготовка визуального контента, аналитика трафика.",
        "description_kz": "«KarMedia» ЖШС контент-менеджер іздейді. Сайттарды контентпен толтыру, SEO-мәтіндер жазу, CMS (WordPress) жұмыс, визуалды контент дайындау, трафик аналитикасы.",
        "requirements_ru": "Опыт от 1 года. WordPress. SEO-основы. Навыки копирайтинга. Canva/Figma.",
        "requirements_kz": "1 жылдан астам тәжірибе. WordPress. SEO негіздері. Копирайтинг дағдылары. Canva/Figma.",
        "employment_type": "full_time",
        "work_type": "hybrid",
        "salary_min": 180000,
        "salary_max": 280000,
        "experience_years": 1,
        "company_name": "KarMedia",
        "contact_email": "hr@karmedia.kz",
        "deadline": 30,
        "skills": [13, 16, 18],
    },
    {
        "profession_id": 11,
        "title_ru": "Корпоративный юрист",
        "title_kz": "Корпоративтік заңгер",
        "description_ru": "АрселорМиттал Темиртау ищет корпоративного юриста. Правовое сопровождение деятельности предприятия, договорная работа, представительство в суде, работа с госорганами, трудовое право.",
        "description_kz": "АрселорМиттал Теміртау корпоративтік заңгер іздейді. Кәсіпорын қызметін құқықтық сүйемелдеу, шарттық жұмыс, сотта өкілдік ету, мемлекеттік органдармен жұмыс.",
        "requirements_ru": "Высшее юридическое. Опыт от 3 лет. Корпоративное и трудовое право. Английский — плюс.",
        "requirements_kz": "Жоғары заң білімі. 3 жылдан астам тәжірибе. Корпоративтік және еңбек құқығы.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 400000,
        "salary_max": 650000,
        "experience_years": 3,
        "company_name": "АрселорМиттал Темиртау",
        "contact_email": "legal@arcelormittal.kz",
        "deadline": 30,
        "skills": [12, 13, 14],
    },
    {
        "profession_id": 6,
        "title_ru": "Заведующий складом",
        "title_kz": "Қойма меңгерушісі",
        "description_ru": "ТОО «КарЛогистик» ищет заведующего складом. Управление складским хозяйством, контроль приёмки и отгрузки товаров, инвентаризация, работа с WMS-системой, управление персоналом склада.",
        "description_kz": "«ҚарЛогистик» ЖШС қойма меңгерушісін іздейді. Қойма шаруашылығын басқару, тауарларды қабылдау мен жөнелтуді бақылау, инвентаризация, WMS-жүйемен жұмыс.",
        "requirements_ru": "Опыт управления складом от 2 лет. WMS-системы. 1С:Склад. Внимательность.",
        "requirements_kz": "2 жылдан астам қойманы басқару тәжірибесі. WMS-жүйелер. 1С:Қойма. Мұқияттылық.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 250000,
        "salary_max": 380000,
        "experience_years": 2,
        "company_name": "КарЛогистик",
        "contact_email": "hr@karlogistic.kz",
        "deadline": 30,
        "skills": [14, 15],
    },
    {
        "profession_id": 1,
        "title_ru": "iOS Developer (Swift)",
        "title_kz": "iOS бағдарламашы (Swift)",
        "description_ru": "SatPay ищет iOS-разработчика. Разработка мобильного банковского приложения на Swift, UIKit/SwiftUI, интеграция с платёжными API, биометрическая авторизация, push-уведомления.",
        "description_kz": "SatPay iOS-бағдарламашыны іздейді. Swift-те мобильді банктік қосымшаны әзірлеу, UIKit/SwiftUI, төлем API-мен интеграция, биометриялық авторизация.",
        "requirements_ru": "Swift 2+ лет. UIKit/SwiftUI. REST API. Git. CI/CD. Push-уведомления.",
        "requirements_kz": "Swift 2+ жыл. UIKit/SwiftUI. REST API. Git. CI/CD. Push-хабарламалар.",
        "employment_type": "full_time",
        "work_type": "hybrid",
        "salary_min": 500000,
        "salary_max": 900000,
        "experience_years": 2,
        "company_name": "SatPay",
        "contact_email": "ios@satpay.kz",
        "deadline": 45,
        "skills": [6, 12],
    },
    {
        "profession_id": 3,
        "title_ru": "Системный аналитик",
        "title_kz": "Жүйелік талдаушы",
        "description_ru": "Kazakhmys Digital ищет системного аналитика. Анализ и документирование требований для промышленных IT-систем, проектирование интеграций, написание спецификаций API, моделирование в BPMN/UML.",
        "description_kz": "Kazakhmys Digital жүйелік талдаушыны іздейді. Өнеркәсіптік IT-жүйелер үшін талаптарды талдау және құжаттау, интеграцияларды жобалау, API спецификацияларын жазу.",
        "requirements_ru": "Опыт аналитики от 2 лет. BPMN, UML. REST API/OpenAPI. SQL. Confluence.",
        "requirements_kz": "2 жылдан астам талдау тәжірибесі. BPMN, UML. REST API/OpenAPI. SQL. Confluence.",
        "employment_type": "full_time",
        "work_type": "office",
        "salary_min": 400000,
        "salary_max": 700000,
        "experience_years": 2,
        "company_name": "Kazakhmys Digital",
        "contact_email": "analytics@kazakhmys.com",
        "deadline": 30,
        "skills": [5, 11, 13],
    },
]


def seed_reference_data(db: Session):
    """Seed regions, cities, professions, and skills."""
    print("Seeding regions...")
    for r in REGIONS:
        existing = db.query(Region).filter(Region.id == r["id"]).first()
        if not existing:
            db.add(Region(id=r["id"], name_ru=r["name_ru"], name_kz=r["name_kz"]))
    db.commit()
    print(f"  -> {len(REGIONS)} regions ready")

    print("Seeding cities...")
    for c in CITIES:
        existing = db.query(City).filter(City.id == c["id"]).first()
        if not existing:
            db.add(City(id=c["id"], region_id=c["region_id"], name_ru=c["name_ru"], name_kz=c["name_kz"]))
    db.commit()
    print(f"  -> {len(CITIES)} cities ready")

    print("Seeding professions...")
    for p in PROFESSIONS:
        existing = db.query(Profession).filter(Profession.id == p["id"]).first()
        if not existing:
            db.add(Profession(id=p["id"], name_ru=p["name_ru"], name_kz=p["name_kz"], category=p["category"]))
    db.commit()
    print(f"  -> {len(PROFESSIONS)} professions ready")

    print("Seeding skills...")
    for s in SKILLS:
        existing = db.query(Skill).filter(Skill.id == s["id"]).first()
        if not existing:
            db.add(Skill(id=s["id"], name_ru=s["name_ru"], name_kz=s["name_kz"], category=s["category"]))
    db.commit()
    print(f"  -> {len(SKILLS)} skills ready")


def seed_vacancies(db: Session):
    """Seed 50 Karaganda vacancies parsed from hh.kz."""
    city_id = 1  # Караганда
    print(f"\nSeeding {len(VACANCIES)} Karaganda vacancies...")
    created = 0
    for i, v in enumerate(VACANCIES, 1):
        existing = db.query(Vacancy).filter(
            Vacancy.title_ru == v["title_ru"],
            Vacancy.company_name == v["company_name"]
        ).first()
        if existing:
            print(f"  [{i}] SKIP (exists): {v['title_ru']} @ {v['company_name']}")
            continue

        deadline = date.today() + timedelta(days=v.get("deadline", 30))
        skill_ids = v.pop("skills", [])

        vacancy = Vacancy(
            profession_id=v["profession_id"],
            city_id=city_id,
            title_kz=v["title_kz"],
            title_ru=v["title_ru"],
            description_kz=v["description_kz"],
            description_ru=v["description_ru"],
            requirements_kz=v.get("requirements_kz"),
            requirements_ru=v.get("requirements_ru"),
            employment_type=v["employment_type"],
            work_type=v["work_type"],
            salary_min=v.get("salary_min"),
            salary_max=v.get("salary_max"),
            experience_years=v.get("experience_years"),
            contact_email=v["contact_email"],
            company_name=v.get("company_name"),
            deadline=deadline,
            is_active=True,
            moderation_status="approved",
            moderated_at=datetime.utcnow(),
            is_admin_created=True,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        )
        db.add(vacancy)
        db.flush()

        for skill_id in skill_ids:
            db.execute(
                vacancy_skills.insert().values(
                    vacancy_id=vacancy.id,
                    skill_id=skill_id
                )
            )

        created += 1
        print(f"  [{i}] OK: {v['title_ru']} @ {v['company_name']}")

    db.commit()
    print(f"\n  -> {created} vacancies created")


def main():
    print("=" * 60)
    print("SARYARQA JASTARY - Karaganda Vacancy Seed Script")
    print("Source: hh.kz (Karaganda vacancies)")
    print("=" * 60)

    db = SessionLocal()
    try:
        seed_reference_data(db)
        seed_vacancies(db)
        print("\n" + "=" * 60)
        print("Seeding complete!")
        print("=" * 60)
    except Exception as e:
        db.rollback()
        print(f"\nERROR: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
